FROM        python:alpine

LABEL       maintainer="ksurl"

WORKDIR     /config

VOLUME      /config /downloads /media

EXPOSE      5050

ENV         LOG_FILE=/config/flexget.log \
            LOG_LEVEL=info \
            PUID=1000 \
            PGID=1000 \
            TZ=UTC \
            VERSION=""

RUN         apk add --no-cache --virtual .build-deps \
                gcc \
                make \
                libffi-dev \
                musl-dev

RUN         apk add --no-cache --virtual .run-deps \
                tzdata \
                libressl-dev \
                su-exec \
                netcat-openbsd

RUN         pip install --no-cache-dir \
                dumb-init \
                pysftp==0.2.8 \
                transmissionrpc

RUN         apk del --purge --no-cache .build-deps

RUN         pip install --no-cache-dir flexget && \
            rm -rf /tmp/* /var/cache/apk/* /root/.cache

COPY        init /init
RUN         chmod +x /init

ENTRYPOINT  [ "/usr/local/bin/dumb-init", "--" ]
CMD [ "/init" ]
