FROM        python:alpine

LABEL       maintainer="ksurl"

WORKDIR     /config

VOLUME      /config /downloads /media

EXPOSE      5050

ENV         LOG_FILE=/config/flexget.log \
            LOG_LEVEL=info \
            PUID=1000 \
            PGID=1000 \
            TZ=UTC \
            VERSION=""

COPY        init /init

RUN         chmod +x /init && \
            apk add --no-cache --virtual .run-deps \
                dumb-init \
                libressl-dev \
                su-exec \
                tzdata && \
            pip install --no-cache-dir \
                transmissionrpc \
                flexget && \
            rm -rf /tmp/* /var/cache/apk/* /root/.cache

HEALTHCHECK --interval=60s --timeout=15s --start-period=5s --retries=3 \
            CMD [ "/bin/sh", "-c", "/usr/local/bin/flexget -l /dev/null daemon status | /bin/grep -q 'Daemon running'" ]

ENTRYPOINT  [ "/usr/bin/dumb-init", "--" ]
CMD         [ "/init" ]

