version: "2"
services:
  flexget:
    image: flexget:latest
    container_name: flexget
    hostname: flexget
    command: ["sh","-c","rm -f /config/.config-lock 2> /dev/null && flexget daemon start --autoreload-config" ]
    networks:
      local:
        ipv4_address: 172.20.0.2 # set your own IP here if not using this subnet
    ports:
      - 5050:5050
    volumes:
      - <HOST>/config:/config
      - <HOST_MNT>/downloads/flexget:/downloads
      - <HOST_MNT>/media:/media
      - /etc/localtime:/etc/localtime:ro
    labels:
      com.centurylinklabs.watchtower.enable: "false" # no autoupdate from watchtower
    restart: unless-stopped

  tunnel:
    image: jossec101/sshtunneller:latest
    container_name: tunnel
    networks:
      local:
        ipv4_address: 172.20.0.3 # set your own IP here if not using this subnet
    environment:
      - ssh_host=<REMOTE_SERVER_IP>
      - ssh_port=22 # change if not default port
      - ssh_username=<REMOTE_USERNAME>
      - ssh_private_key_password=<SSH_PRIVATE_KEY_PASSWORD>
      - remote_bind_addresses=[("127.0.0.1",9091)] # change port, add additional with comma separation
      - local_bind_addresses=[("172.20.0.3",9091)] # change port, add additional with comma separation
    volumes:
     - <HOST>/key:/private.key
    restart: unless-stopped
    
networks:
  local:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 # pick your own subnet and fill in gateway/range accordingly
          gateway: 172.20.0.1
          ip_range: 172.20.1.0/24 # pick a range outside of what you plan to use for static IP's