version: "3"
services:
  flexget:
    image: ghcr.io/ksurl/flexget
    container_name: flexget
    environment:
      - LOG_FILE=/config/flexget.log
      - LOG_LEVEL=info
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - VERSION=docker
    ports:
      - 5050:5050
    volumes:
      - <HOST>/config:/config
      - <HOST_MNT>/downloads/flexget:/downloads
      - <HOST_MNT>/media:/media
    restart: unless-stopped
