version: "2"
services:
  flexget:
    image: ksurl/flexget:latest
    container_name: flexget
    environment:
      - LOG_FILE=/config/flexget.log
      - LOG_LEVEL=info
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - VERSION=latest
    ports:
      - 5050:5050
    volumes:
      - <HOST>/config:/config
      - <HOST_MNT>/downloads/flexget:/downloads
      - <HOST_MNT>/media:/media
    labels:
      com.centurylinklabs.watchtower.enable: "false" # no autoupdate from watchtower
    restart: unless-stopped
