#!/bin/sh

rm -f /config/.config-lock 2> /dev/null 

if [ ! -f /config/config.yml ]; then
  echo "no config file found."
  exit
fi

cp "/usr/share/zoneinfo/${TZ}" /etc/localtime && echo "${TZ}" > /etc/timezone
LOGFILE="--logfile ${LOG_FILE}"
LOGLEVEL="--loglevel ${LOG_LEVEL}"

case ${VERSION} in
  latest)
    pip install -U flexget
    ;;
  "")
    flexget -V
    ;;
  *)
    pip install -U "flexget==${VERSION}"
    ;;
esac

su-exec ${PUID}:${PGID} /usr/local/bin/flexget -c /config/config.yml $LOGFILE $LOGLEVEL daemon start --autoreload-config
