#!/command/with-contenv bash

# set UID and GID
PUID=${PUID:-911}
PGID=${PGID:-911}

groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"

# set permissions
chown abc:abc /defaults

# set timezone
echo "Setting timezone to $TZ."
cp -f "/usr/share/zoneinfo/${TZ}" /etc/localtime && echo "${TZ}" > /etc/timezone

# lock file cleanup
rm -f /config/.config-lock 2>/dev/null

# default config
if [ ! -f /config/config.yml ]; then
  cp -f /defaults/config.yml /config/config.yml
fi

# permissions
chown -R abc:abc /config
if [ -d /data/downloads/flexget ]; then
  chown abc:abc /data/downloads/flexget
fi

# set flexget version to install
case ${VERSION} in
  latest)
    echo "Updating to latest version of FlexGet."
    pip install -U flexget
    ;;
  docker)
    echo "Checking FlexGet version..."
    flexget -V
    ;;
  *)
    echo "Installing FlexGet $VERSION."
    pip install -U "flexget==${VERSION}"
    ;;
esac
