name: bump

on:
  push:
    branches:
      - main
    paths:
      - requirements.txt

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Bump version
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TAG_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: false
